[workspace]
resolver = "3"
members = [
  "crates/agent",
  "crates/chat",
  "crates/brick",
  "crates/brick_macro",
  "crates/content",
  "crates/gateway",
  "crates/message",
  "crates/ui",
  "crates/ui_macro",
]

[workspace.dependencies]
dioxus = { version = "0.7.2" }
bon = "3.8.1"
regex = { version = "1" }
proc-macro2 = { version = "1.0.103", features = ["span-locations"] }
quote = "1.0.42"
syn = { version = "2.0.111", features = ["extra-traits", "full"] }
anyhow = "1.0.100"
axum = "0.8.7"
axum-extra = { version = "0.12" }
figment = { version = "0.10.19", features = ["toml", "env"] }
futures = "0.3.31"
futures-util = "0.3.31"
sqlx = { version = "0.8.6" }
tokio-postgres = { version = "0.7.15" }
refinery = { version = "0.9.0" }
minijinja = { version = "2.13.0", features = ["loader"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_derive = "1.0.228"
serde_json = "1.0.145"
serde_with = "3.16.1"
short-uuid = "0.2.0"
itertools = "0.14.0"
time = "0.3.44"
chrono = { version = "0.4.42", features = ["serde"] }
reqwest = { version = "0.12.25", features = ["json"] }
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.43"
tracing-serde = "0.2.0"
tracing-subscriber = { version = "0.3.22", features = ["json", "env-filter"] }
url = "2.5.7"
async-fs = "2.2.0"
serde_yaml = "0.9.34"
maplit = "1.0.2"
urlencoding = "2.1.3"
indoc = "2.0.7"
indexmap = { version = "2.12.1", features = ["serde"] }
tower-http = { version = "0.6.8", features = ["fs"] }
rdkafka = { version = "0.38", features = ["cmake-build"] }
iggy = "0.8.0"
bincode = "2.0.1"

tracing-wasm = "0.2.1"
gloo-net = "0.6.0"
js-sys = "0.3.83"
markdown = "1.0.0"
web-sys = "0.3.83"

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3

