[workspace]
resolver = "3"
members = [
  "crates/agent",
  "crates/chat",
  "crates/brick",
  "crates/brick_macro",
  "crates/content",
  "crates/gateway",
  "crates/kafka",
  "crates/message",
  "crates/ui",
  "crates/ui_macro"
]

[workspace.dependencies]
proc-macro2 = { version = "1.0.103", features = ["span-locations"] }
quote = "1.0.42"
syn = { version = "2.0.110", features = ["extra-traits", "full"] }
anyhow = "1.0.100"
axum = "0.8.7"
figment = { version = "0.10.19", features = ["toml", "env"] }
futures = "0.3.31"
minijinja = { version = "2.12.0", features = ["loader"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_derive = "1.0.228"
serde_json = "1.0.145"
serde_with = "3.16.0"
short-uuid = "0.2.0"
itertools = "0.14.0"
time = "0.3.44"
chrono = { version = "0.4.42", features = ["serde"] }
reqwest = { version = "0.12.24", features = ["json"] }
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.41"
tracing-serde = "0.2.0"
tracing-subscriber = { version = "0.3.20", features = ["json", "env-filter"] }
url = "2.5.7"
async-fs = "2.2.0"
serde_yaml = "0.9.34"
maplit = "1.0.2"
urlencoding = "2.1.3"
indoc = "2.0.7"
indexmap = { version = "2.12.1", features = ["serde"] }

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"

