login_with_cookie = true
[trace]
format = 'compact'

[queue.outgo]
type = 'kafka'
broker = ['localhost:19092']
topic = 'event'

[queue.income]
type = 'kafka'
broker = ['localhost:19092']
topic = ['push']
group = 'ws'

# [queue.outgo]
# type = 'iggy'
# broker = '127.0.0.1:8096'
# username = 'iggy'
# password = 'iggy'
# stream = 'fluxora'
# topic = 'event'

# [queue.income]
# type = 'iggy'
# broker = '127.0.0.1:8096'
# username = 'iggy'
# password = 'iggy'
# stream = 'fluxora'
# topic = 'push'
# group = 'ws'

[hooks.login]
endpoint = 'http://localhost:3000/debug/login'

[hooks.logout]
endpoint = 'http://localhost:3000/debug/logout'

[[hooks.greet]]
disable = false
endpoint = 'http://localhost:3000/debug/render/layout.json'

[[hooks.greet]]
disable = false
path = 'user.json'

[[hooks.greet]]
disable = false
path = 'segment.tmpl.json'

[hooks.history]
disable = false
endpoint = 'http://localhost:8000/v1/history'

[hooks.echo]
endpoint = 'http://localhost:3000/debug/echo'

[hooks.render]
endpoint = 'http://localhost:3000/debug/render/layout.json'

