name: chef

on:
  push:
    branches: [ release ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: fj0r/fluxora


jobs:
  build:

    runs-on: ubuntu-latest
    # if: ${{ startsWith(github.event.head_commit.message, 'ğŸ—ï¸') }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: fj0r
          password: ${{ secrets.GHCR_TOKEN }}

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            lock:
              - 'Cargo.lock'

      - name: Set up Docker Buildx
        if: steps.changes.outputs.lock == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        if: steps.changes.outputs.lock == 'true'
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-edap
          restore-keys: |
            ${{ runner.os }}-buildx-edap

      - name: Get PR head commit title
        id: commit
        run: |
          MESSAGE=$(git log -1 --pretty=%s ${{ github.event.pull_request.head.sha }})
          echo "message=$MESSAGE" >> "$GITHUB_OUTPUT"

      - name: Clean cache
        if: ${{ contains(steps.commit.outputs.message, 'ğŸ—‘ï¸') }}
        run: |
          rm -rf /tmp/.buildx-cache

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build
        uses: docker/build-push-action@v4
        if: steps.changes.outputs.lock == 'true'
        with:
          file: docker/chef.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:chef
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        if: steps.changes.outputs.lock == 'true'
        # ä¸´æ—¶è§£å†³ç¼“å­˜å¤§å°é—®é¢˜ã€turn0search3ã€‘
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

